// Package controller implements the operator-only reconcile logic for the
// Kryton CRD: backup CronJobs, plugin init-container injection, and
// VolumeSnapshot scheduling.
//
// The helm-based reconciler (see internal/helm) owns Deployment/Service/etc.;
// this controller layers operator-specific resources on top of that release.
package controller

import (
	"context"

	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// KrytonExtrasReconciler reconciles the operator-only fields of a Kryton CR.
type KrytonExtrasReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=kryton.azrtydxb.io,resources=krytons,verbs=get;list;watch
// +kubebuilder:rbac:groups=kryton.azrtydxb.io,resources=krytons/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=batch,resources=cronjobs;jobs,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=secrets;configmaps;persistentvolumeclaims,verbs=get;list;watch;create;update;patch
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;update;patch
// +kubebuilder:rbac:groups=snapshot.storage.k8s.io,resources=volumesnapshots;volumesnapshotclasses,verbs=get;list;watch;create;update;patch;delete

// Reconcile dispatches to the three operator-only sub-reconcilers.
func (r *KrytonExtrasReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := ctrl.LoggerFrom(ctx).WithValues("kryton", req.NamespacedName)
	log.V(1).Info("reconciling operator-only fields")

	// Implementation outline (full bodies live in backup.go / plugins.go /
	// snapshot.go siblings in this package once the CRD Go types are
	// generated by `make generate` after C8 lands):
	//
	//   var kr v1alpha1.Kryton
	//   if err := r.Get(ctx, req.NamespacedName, &kr); err != nil {
	//       return ctrl.Result{}, client.IgnoreNotFound(err)
	//   }
	//   if err := r.reconcileBackup(ctx, &kr); err != nil { return ctrl.Result{}, err }
	//   if err := r.reconcilePlugins(ctx, &kr); err != nil { return ctrl.Result{}, err }
	//   if err := r.reconcileSnapshot(ctx, &kr); err != nil { return ctrl.Result{}, err }
	//
	return ctrl.Result{}, nil
}

// SetupWithManager wires the controller into the manager.
func (r *KrytonExtrasReconciler) SetupWithManager(mgr ctrl.Manager) error {
	// Real wiring once v1alpha1 Go types are generated:
	//   return ctrl.NewControllerManagedBy(mgr).
	//       For(&v1alpha1.Kryton{}).
	//       Owns(&batchv1.CronJob{}).
	//       Owns(&snapshotv1.VolumeSnapshot{}).
	//       Complete(r)
	_ = mgr
	return nil
}
