#!/usr/bin/env node
/**
 * Generates `src/_version.ts` from package.json so the published bundle
 * always reports the version that was actually built. Run as a prebuild
 * step; the generated file is committed so dev typecheck/test work
 * without manually running the script.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");
const pkg = JSON.parse(readFileSync(resolve(pkgRoot, "package.json"), "utf8"));
const target = resolve(pkgRoot, "src", "_version.ts");

const body = `// AUTO-GENERATED by scripts/sync-version.mjs from package.json.
// Do not edit by hand — runs as a prebuild step.
export const KRYTON_UI_VERSION = ${JSON.stringify(pkg.version)};
`;

writeFileSync(target, body);
process.stdout.write(`wrote ${target} (version ${pkg.version})\n`);
