//go:build !ignore_autogenerated

// Code generated by hand (helm-sdk layout has no controller-gen).
// Keep in sync with kryton_types.go.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies into out.
func (in *Kryton) DeepCopyInto(out *Kryton) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy.
func (in *Kryton) DeepCopy() *Kryton {
	if in == nil {
		return nil
	}
	out := new(Kryton)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Kryton) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies into out.
func (in *KrytonList) DeepCopyInto(out *KrytonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Kryton, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy returns a deep copy.
func (in *KrytonList) DeepCopy() *KrytonList {
	if in == nil {
		return nil
	}
	out := new(KrytonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *KrytonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies into out.
func (in *KrytonSpec) DeepCopyInto(out *KrytonSpec) {
	*out = *in
	if in.Values != nil {
		out.Values = in.Values.DeepCopy()
	}
	if in.Backup != nil {
		out.Backup = new(BackupSpec)
		in.Backup.DeepCopyInto(out.Backup)
	}
	if in.Plugins != nil {
		out.Plugins = make([]Plugin, len(in.Plugins))
		copy(out.Plugins, in.Plugins)
	}
	if in.Snapshot != nil {
		out.Snapshot = new(SnapshotSpec)
		*out.Snapshot = *in.Snapshot
	}
	_ = apiextensionsv1.JSON{}
}

// DeepCopy returns a deep copy.
func (in *KrytonSpec) DeepCopy() *KrytonSpec {
	if in == nil {
		return nil
	}
	out := new(KrytonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies into out.
func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
	if in.ObjectStore != nil {
		out.ObjectStore = new(ObjectStore)
		in.ObjectStore.DeepCopyInto(out.ObjectStore)
	}
}

// DeepCopy returns a deep copy.
func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies into out.
func (in *ObjectStore) DeepCopyInto(out *ObjectStore) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		out.CredentialsSecretRef = new(SecretRef)
		*out.CredentialsSecretRef = *in.CredentialsSecretRef
	}
}

// DeepCopy returns a deep copy.
func (in *ObjectStore) DeepCopy() *ObjectStore {
	if in == nil {
		return nil
	}
	out := new(ObjectStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies into out.
func (in *KrytonStatus) DeepCopyInto(out *KrytonStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// DeepCopy returns a deep copy.
func (in *KrytonStatus) DeepCopy() *KrytonStatus {
	if in == nil {
		return nil
	}
	out := new(KrytonStatus)
	in.DeepCopyInto(out)
	return out
}
