{{- if .Values.externalSecrets.enabled -}}
{{- if not .Values.externalSecrets.secretStoreName -}}
{{- fail "externalSecrets.enabled=true requires externalSecrets.secretStoreName" -}}
{{- end -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "kryton.secretName" . }}
  labels:
    {{- include "kryton.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ include "kryton.secretName" . }}
    creationPolicy: Owner
  data:
    {{- $prefix := .Values.externalSecrets.remoteKeyPrefix }}
    {{- range $k, $v := .Values.env.secret }}
    - secretKey: {{ $k }}
      remoteRef:
        key: {{ printf "%s%s" $prefix (default $k $v) | quote }}
    {{- end }}
{{- end }}
