{{- if not .Values.externalSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kryton.secretName" . }}
  labels:
    {{- include "kryton.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.env.secret }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
