apiVersion: kryton.azrtydxb.io/v1alpha1
kind: Kryton
metadata:
  name: kryton-sample
spec:
  # Default values copied from <project_dir>/helm-charts/kryton/values.yaml
  env: {}
  externalSecrets:
    enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/azrtydxb/kryton/kryton
    tag: latest
  ingress:
    enabled: false
  persistence:
    enabled: false
  postgresql:
    enabled: false
  replicaCount: 1
  service:
    port: 3000
    type: ClusterIP
  
  
